{
  qwen_2b: [
    { label: "BF16", filename: "Qwen3.5-2B-BF16.gguf" },
    { label: "IQ4_NL", filename: "Qwen3.5-2B-IQ4_NL.gguf" },
    { label: "IQ4_XS", filename: "Qwen3.5-2B-IQ4_XS.gguf" },
    { label: "Q3_K_M", filename: "Qwen3.5-2B-Q3_K_M.gguf" },
    { label: "Q3_K_S", filename: "Qwen3.5-2B-Q3_K_S.gguf" },
    { label: "Q4_0", filename: "Qwen3.5-2B-Q4_0.gguf" },
    { label: "Q4_1", filename: "Qwen3.5-2B-Q4_1.gguf" },
    { label: "Q4_K_M", filename: "Qwen3.5-2B-Q4_K_M.gguf" },
    { label: "Q4_K_S", filename: "Qwen3.5-2B-Q4_K_S.gguf" },
    { label: "Q5_K_M", filename: "Qwen3.5-2B-Q5_K_M.gguf" },
    { label: "Q5_K_S", filename: "Qwen3.5-2B-Q5_K_S.gguf" },
    { label: "Q6_K", filename: "Qwen3.5-2B-Q6_K.gguf" },
    { label: "Q8_0", filename: "Qwen3.5-2B-Q8_0.gguf" },
    { label: "UD-IQ2_M", filename: "Qwen3.5-2B-UD-IQ2_M.gguf" },
    { label: "UD-IQ2_XXS", filename: "Qwen3.5-2B-UD-IQ2_XXS.gguf" },
    { label: "UD-IQ3_XXS", filename: "Qwen3.5-2B-UD-IQ3_XXS.gguf" },
    { label: "UD-Q2_K_XL", filename: "Qwen3.5-2B-UD-Q2_K_XL.gguf" },
    { label: "UD-Q3_K_XL", filename: "Qwen3.5-2B-UD-Q3_K_XL.gguf" },
    { label: "UD-Q4_K_XL", filename: "Qwen3.5-2B-UD-Q4_K_XL.gguf" },
    { label: "UD-Q5_K_XL", filename: "Qwen3.5-2B-UD-Q5_K_XL.gguf" },
    { label: "UD-Q6_K_XL", filename: "Qwen3.5-2B-UD-Q6_K_XL.gguf" },
    { label: "UD-Q8_K_XL", filename: "Qwen3.5-2B-UD-Q8_K_XL.gguf" },
  ],
}